###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class AltNames(BaseModel):
    alt_names: List[str]

class CardiacDecision(BaseModel):
    answer: Optional[Union[Literal["Yes"], Literal["No"]]] = None

class Entities(BaseModel):
    entities: List[str]

class EvaluatedTriple(BaseModel):
    head: Optional[str] = None
    relation: Optional[Literal["INTERACTS_WITH"]] = None
    tail: Optional[str] = None
    score: Optional[int] = None
    evidence: Optional[str] = None

class ExtractionStrategies(BaseModel):
    strategies: List["ExtractionStrategy"]

class ExtractionStrategy(BaseModel):
    name: Optional[str] = None
    focus: Optional[str] = None
    avoid: Optional[str] = None

class Judgement(BaseModel):
    judgement: Optional[Union[Literal["correct"], Literal["incorrect"]]] = None

class Message(BaseModel):
    role: Optional[Union[Literal["user"], Literal["assistant"]]] = None
    content: Optional[str] = None

class PathEvaluation(BaseModel):
    evaluated_triples: List["EvaluatedTriple"]
    summary: Optional[str] = None

class Reason(BaseModel):
    reason: Optional[str] = None

class Triple(BaseModel):
    model_config = ConfigDict(extra='allow')
    head: Optional[str] = None
    relation: Optional[Literal["INTERACTS_WITH"]] = None
    tail: Optional[str] = None

class Triples(BaseModel):
    triples: List["Triple"]
