###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import typing
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder
from baml_py.type_builder import TypeBuilder as _TypeBuilder, ClassPropertyBuilder, ClassPropertyViewer, EnumValueViewer
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


class TypeBuilder(_TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["AltNames","CardiacDecision","Entities","EvaluatedTriple","ExtractionStrategies","ExtractionStrategy","Judgement","Message","PathEvaluation","Reason","Triple","Triples",]
        ), enums=set(
          []
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)


    @property
    def AltNames(self) -> "AltNamesAst":
        return AltNamesAst(self)

    @property
    def CardiacDecision(self) -> "CardiacDecisionAst":
        return CardiacDecisionAst(self)

    @property
    def Entities(self) -> "EntitiesAst":
        return EntitiesAst(self)

    @property
    def EvaluatedTriple(self) -> "EvaluatedTripleAst":
        return EvaluatedTripleAst(self)

    @property
    def ExtractionStrategies(self) -> "ExtractionStrategiesAst":
        return ExtractionStrategiesAst(self)

    @property
    def ExtractionStrategy(self) -> "ExtractionStrategyAst":
        return ExtractionStrategyAst(self)

    @property
    def Judgement(self) -> "JudgementAst":
        return JudgementAst(self)

    @property
    def Message(self) -> "MessageAst":
        return MessageAst(self)

    @property
    def PathEvaluation(self) -> "PathEvaluationAst":
        return PathEvaluationAst(self)

    @property
    def Reason(self) -> "ReasonAst":
        return ReasonAst(self)

    
    @property
    def Triple(self) -> "TripleBuilder":
        return TripleBuilder(self)

    @property
    def Triples(self) -> "TriplesAst":
        return TriplesAst(self)





class AltNamesAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("AltNames")
        self._properties: typing.Set[str] = set([ "alt_names", ])
        self._props = AltNamesProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "AltNamesProperties":
        return self._props


class AltNamesViewer(AltNamesAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class AltNamesProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def alt_names(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("alt_names"))

    

class CardiacDecisionAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("CardiacDecision")
        self._properties: typing.Set[str] = set([ "answer", ])
        self._props = CardiacDecisionProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "CardiacDecisionProperties":
        return self._props


class CardiacDecisionViewer(CardiacDecisionAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class CardiacDecisionProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def answer(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("answer"))

    

class EntitiesAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Entities")
        self._properties: typing.Set[str] = set([ "entities", ])
        self._props = EntitiesProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "EntitiesProperties":
        return self._props


class EntitiesViewer(EntitiesAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class EntitiesProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def entities(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("entities"))

    

class EvaluatedTripleAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("EvaluatedTriple")
        self._properties: typing.Set[str] = set([ "head",  "relation",  "tail",  "score",  "evidence", ])
        self._props = EvaluatedTripleProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "EvaluatedTripleProperties":
        return self._props


class EvaluatedTripleViewer(EvaluatedTripleAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class EvaluatedTripleProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def head(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("head"))

    @property
    def relation(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("relation"))

    @property
    def tail(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("tail"))

    @property
    def score(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("score"))

    @property
    def evidence(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("evidence"))

    

class ExtractionStrategiesAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ExtractionStrategies")
        self._properties: typing.Set[str] = set([ "strategies", ])
        self._props = ExtractionStrategiesProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ExtractionStrategiesProperties":
        return self._props


class ExtractionStrategiesViewer(ExtractionStrategiesAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class ExtractionStrategiesProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def strategies(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("strategies"))

    

class ExtractionStrategyAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ExtractionStrategy")
        self._properties: typing.Set[str] = set([ "name",  "focus",  "avoid", ])
        self._props = ExtractionStrategyProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ExtractionStrategyProperties":
        return self._props


class ExtractionStrategyViewer(ExtractionStrategyAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class ExtractionStrategyProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def name(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("name"))

    @property
    def focus(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("focus"))

    @property
    def avoid(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("avoid"))

    

class JudgementAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Judgement")
        self._properties: typing.Set[str] = set([ "judgement", ])
        self._props = JudgementProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "JudgementProperties":
        return self._props


class JudgementViewer(JudgementAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class JudgementProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def judgement(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("judgement"))

    

class MessageAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Message")
        self._properties: typing.Set[str] = set([ "role",  "content", ])
        self._props = MessageProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "MessageProperties":
        return self._props


class MessageViewer(MessageAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class MessageProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def role(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("role"))

    @property
    def content(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("content"))

    

class PathEvaluationAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("PathEvaluation")
        self._properties: typing.Set[str] = set([ "evaluated_triples",  "summary", ])
        self._props = PathEvaluationProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "PathEvaluationProperties":
        return self._props


class PathEvaluationViewer(PathEvaluationAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class PathEvaluationProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def evaluated_triples(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("evaluated_triples"))

    @property
    def summary(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("summary"))

    

class ReasonAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Reason")
        self._properties: typing.Set[str] = set([ "reason", ])
        self._props = ReasonProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ReasonProperties":
        return self._props


class ReasonViewer(ReasonAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class ReasonProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def reason(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("reason"))

    

class TripleAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Triple")
        self._properties: typing.Set[str] = set([ "head",  "relation",  "tail", ])
        self._props = TripleProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "TripleProperties":
        return self._props


class TripleBuilder(TripleAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    def add_property(self, name: str, type: FieldType) -> ClassPropertyBuilder:
        if name in self._properties:
            raise ValueError(f"Property {name} already exists.")
        return ClassPropertyBuilder(self._bldr.property(name).type(type))

    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyBuilder]]:
        return [(name, ClassPropertyBuilder(self._bldr.property(name))) for name in self._properties]



class TripleProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def head(self) -> ClassPropertyBuilder:
        return ClassPropertyBuilder(self.__bldr.property("head"))

    @property
    def relation(self) -> ClassPropertyBuilder:
        return ClassPropertyBuilder(self.__bldr.property("relation"))

    @property
    def tail(self) -> ClassPropertyBuilder:
        return ClassPropertyBuilder(self.__bldr.property("tail"))

    
    def __getattr__(self, name: str) -> ClassPropertyBuilder:
        if name not in self.__properties:
            raise AttributeError(f"Property {name} not found.")
        return ClassPropertyBuilder(self.__bldr.property(name))
    

class TriplesAst:
    def __init__(self, tb: _TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Triples")
        self._properties: typing.Set[str] = set([ "triples", ])
        self._props = TriplesProperties(self._bldr, self._properties)

    def type(self) -> FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "TriplesProperties":
        return self._props


class TriplesViewer(TriplesAst):
    def __init__(self, tb: _TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, ClassPropertyViewer]]:
        return [(name, ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]



class TriplesProperties:
    def __init__(self, bldr: ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties

    

    @property
    def triples(self) -> ClassPropertyViewer:
        return ClassPropertyViewer(self.__bldr.property("triples"))

    




__all__ = ["TypeBuilder"]