###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Literal, Optional, TypeVar, Union


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str

class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class AltNames(BaseModel):
    alt_names: List[str]

class CardiacDecision(BaseModel):
    answer: Union[Literal["Yes"], Literal["No"]]

class Entities(BaseModel):
    entities: List[str]

class EvaluatedTriple(BaseModel):
    head: str
    relation: Literal["INTERACTS_WITH"]
    tail: str
    score: int
    evidence: str

class ExtractionStrategies(BaseModel):
    strategies: List["ExtractionStrategy"]

class ExtractionStrategy(BaseModel):
    name: str
    focus: str
    avoid: str

class Judgement(BaseModel):
    judgement: Union[Literal["correct"], Literal["incorrect"]]

class Message(BaseModel):
    role: Union[Literal["user"], Literal["assistant"]]
    content: str

class PathEvaluation(BaseModel):
    evaluated_triples: List["EvaluatedTriple"]
    summary: str

class Reason(BaseModel):
    reason: str

class Triple(BaseModel):
    model_config = ConfigDict(extra='allow')
    head: str
    relation: Literal["INTERACTS_WITH"]
    tail: str

class Triples(BaseModel):
    triples: List["Triple"]
